decrypt:
  settings.xml: "repo/settings.xml.asc"
  pubring.gpg: "repo/pubring.gpg.asc"
  secring.gpg: "repo/secring.gpg.asc"
release:
  script: |
    mvn versions:set "-DnewVersion=${tag}"
    git status
    git commit -a -m "${tag}" --allow-empty
    mvn --settings /home/r/settings.xml clean deploy
